import {StyleSheet} from 'react-native';
import Color from '../../themes/Colors';
import {FONT_SIZE, HEIGHT, SPACING, WIDTH} from '../../themes/Constants';
export default StyleSheet.create({
  box: {
    paddingVertical: SPACING.v20,
    marginHorizontal: SPACING.v15,
    borderRadius: SPACING.v8,
    backgroundColor: Color.white,
    borderWidth: 0.3,
    borderColor: Color.txtDark,
  },
  checkBoxView: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  buttonStyle: {
    alignSelf: 'center',
    borderWidth: 0.5,
    borderColor: Color.txtDark,
    borderRadius: SPACING.v8,
    paddingHorizontal: SPACING.v20,
    width: '45%',
    backgroundColor: Color.white,
    marginHorizontal: SPACING.v5,
    marginBottom: SPACING.v10,
    height: HEIGHT.h40,
  },
  icon: {
    height: 60,
    width: 60,
    alignSelf: 'center',
    marginBottom: SPACING.v15,
  },
  buttonText: {
    fontSize: FONT_SIZE.f15,
    paddingVertical: SPACING.v8,
    color: Color.black,
    fontWeight: '600',
  },
  inputBox: {
    alignSelf: 'center',
    borderWidth: 0.5,
    borderColor: Color.txtDark,
    borderRadius: SPACING.v8,
    paddingHorizontal: SPACING.v20,
    width: '90%',
    marginBottom: SPACING.v10,
    marginHorizontal: SPACING.v15,
    fontSize: FONT_SIZE.f13,
    color: Color.black,
    fontWeight: '400',
    height: HEIGHT.h70,
    textAlignVertical: 'top',
  },
  bottomButton: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginHorizontal: SPACING.v15,
    alignItems: 'center',
  },
  bottomButtonStyle: {
    borderBottomWidth: 0.5,
    borderColor: Color.txtDark,
    borderRadius: SPACING.v8,
    width: '45%',
    marginBottom: SPACING.v10,
    backgroundColor: Color.white,
  },
  bottomInputBox: {
    borderBottomWidth: 0.5,
    borderColor: Color.txtDark,
    borderRadius: SPACING.v8,
    paddingHorizontal: SPACING.v20,
    width: '45%',
    marginBottom: SPACING.v10,
    marginHorizontal: SPACING.v15,
    fontSize: FONT_SIZE.f15,
    color: Color.textDark1,
  },
  saveButton: {
    backgroundColor: Color.green,
    width: WIDTH.w150,
    alignSelf: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: SPACING.v8,
    borderRadius: SPACING.v8,
    marginVertical: SPACING.v15,
  },
  saveButtonText: {
    fontSize: FONT_SIZE.f15,
    color: Color.white,
    fontWeight: '600',
  },
});
