import Color from "@theme/colors";
import { SPACING, WIDTH, HEIGHT } from "@theme/constants";
import { StyleSheet } from "react-native";
export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Color.white,
    borderTopLeftRadius: 14,
    borderTopRightRadius: 14,
    overflow: "hidden",
  },
  headerView: {
    backgroundColor: Color.white,
    paddingTop: SPACING.v25,
    paddingBottom: SPACING.v12,
    paddingHorizontal: SPACING.v15,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  headerButton: {
    backgroundColor: Color.black_10,
    paddingVertical: SPACING.v4,
    paddingHorizontal: SPACING.v8,
    borderRadius: SPACING.v12,
  },
  crossIcon: {
    height: WIDTH.w24,
    width: WIDTH.w24,
  },
  scrollView: {
    marginBottom: SPACING.v100,
  },
  imageBorder: {
    alignSelf: "center",
    height: WIDTH.w155,
    width: WIDTH.w155,
    marginBottom: SPACING.v35,
    borderRadius: WIDTH.w155 / 2,
    justifyContent: "center",
    alignItems: "center",
  },
  smaiiImageBorder: {
    alignSelf: "center",
    height: WIDTH.w117,
    width: WIDTH.w117,
    marginBottom: SPACING.v35,
    borderRadius: WIDTH.w117 / 2,
    justifyContent: "center",
    alignItems: "center",
  },
  userIcon: {
    alignSelf: "center",
    height: WIDTH.w150,
    width: WIDTH.w150,
    borderRadius: WIDTH.w150 / 2,
    justifyContent: "center",
    alignItems: "center",
  },
  buttonStyle: {
    marginVertical: SPACING.v15,
  },
  smaiiUserIcon: {
    alignSelf: "center",
    height: WIDTH.w120,
    width: WIDTH.w120,
    borderRadius: WIDTH.w120 / 2,
    justifyContent: "center",
    alignItems: "center",
  },
  recentlySelectedBox: {
    backgroundColor: Color.lightGreen,
    paddingHorizontal: SPACING.v35,
    paddingVertical: SPACING.v8,
    borderRadius: SPACING.v15,
    width: "90%",
    alignSelf: "center",
    marginBottom: SPACING.v15,
  },
  detailView: {
    width: "90%",
    alignSelf: "center",
    marginBottom: SPACING.v15,
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "center",
    justifyContent: "center",
  },
  flatlist: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginHorizontal: SPACING.v20,
    alignSelf: "center",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 19,
  },
  buttonView: {
    marginRight: 3,
    paddingHorizontal: SPACING.v12,
    paddingVertical: SPACING.v6,
    flexDirection: "row",
    marginVertical: 10,
    backgroundColor: Color.primary_10,
    borderRadius: 16,
  },
  modelBox: {
    backgroundColor: Color.transparent,
    paddingHorizontal: SPACING.v20,
    paddingVertical: SPACING.v8,
  },
  border: {
    height: 1,
    backgroundColor: Color.black_10,
  },
  removeButton: {
    alignSelf: "center",
    justifyContent: "center",
    alignItems: "center",
    borderColor: Color.text_dark3,
    borderWidth: 1,
    backgroundColor: Color.white,
    paddingVertical: SPACING.v4,
    paddingHorizontal: SPACING.v8,
    borderRadius: SPACING.v15,
  },
});
